### ISSUE TITLE
How to do a Debian install with only root?

### ISSUE THREAD

**Issue by Impa10r** [highghlow/umbrel-install-script#1]
Hello. I'm eager to try your script, but got stuck at doing a fresh Debian 12 install with only a root account. Debian wants me to create a new user or it won't proceed. Any suggestions?

**Comment by unhighghlow** [comment]
Okay, yes, my bad. I checked and it isn't possible. Create a user account (**not** named `umbrel`) and log in as root (I'll update the readme).

**Comment by Impa10r** [comment]
but many umbrel apps will want user 1000:1000, and my first user will take that id. I will try to create user umbrel right away

**Comment by unhighghlow** [comment]
> but many umbrel apps will want user 1000:1000, and my first user will take that id. I will try to create user umbrel right away

It may fail since the script tries to create `umbrel`. I'll add a check to skip this step if the user already exists.

**Comment by unhighghlow** [comment]
Done

**Comment by Impa10r** [comment]
It worked even without checking for the existing user. A bit annoyed with this warning, but only intend this for testnet currently:
```
- Warning ---------------------------------------------------------------------
| Terminal access is only enabled for debugging purposes. Any modifications   |
| made to the umbrelOS system will not be persisted between software updates. |
| For use-cases where you want to run custom software in a Linux environment, |
| consider using the Portainer app available in the Umbrel App Store.         |
-------------------------------------------------------------------------------
```

**Comment by Impa10r** [comment]
Weird, Umbrel startup screen asked for my name and password, applied that password to the umbrel user (it was shorter initially). The apps get installed into /home/umbrer/umbrel/app-data, but all folders are owned by root. umbrel user has no permissions even to home/umbrel.

**Comment by Impa10r** [comment]
Uff, it did not survive the reboot (VM Ware Workstation):

![image](https://github.com/highghlow/umbrel-install-script/assets/101550606/4bf0961c-99ca-41a3-aefc-54c2310f539a)

**Comment by unhighghlow** [comment]
Made a new issue out of this
