### ISSUE TITLE
Cloning umbrel containers

### ISSUE THREAD

**Issue by mikorist** [highghlow/umbrel-install-script#5]
I was stuck for an hour in the step 5 :

STEP 5/8: Cloning umbrel containers
Getting image source signatures
Copying blob 461246efe0a7 done  
Copying blob c8bc27c5e55c [=============>------------------------] 24.7MiB / 66.6MiB

Here is the updated step_5:

```
step_5() {
    echo STEP 5/8: Cloning umbrel containers
    
    sudo mkdir -p /images
    sudo docker pull getumbrel/tor@$TOR_VERSION
    sudo docker save -o /images/tor.tar getumbrel/tor@$TOR_VERSION

    sudo docker pull getumbrel/auth-server@$AUTH_VERSION
    sudo docker save -o /images/auth.tar getumbrel/auth-server@$AUTH_VERSION
}
```

after
/tmp/uis
STEP 5/8: Cloning umbrel containers
docker.io/getumbrel/tor@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a: Pulling from getumbrel/tor
461246efe0a7: Pull complete 
c8bc27c5e55c: Pull complete 
472ce9feeded: Pull complete 
Digest: sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
Status: Downloaded newer image for getumbrel/tor@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
docker.io/getumbrel/tor@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
docker.io/getumbrel/auth-server@sha256:b4a4b37896911a85fb74fa159e010129abd9dff751a40ef82f724ae066db3c2a: Pulling from getumbrel/auth-server
91f01557fe0d: Pull complete 
ecdd21ad91a4: Pull complete 
72f5a0bbd6d5: Pull complete 
6d65359ecb29: Pull complete 
a9db6797916e: Pull complete 
f4eaccdb25fc: Pull complete 
49e010269d4e: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:b4a4b37896911a85fb74fa159e010129abd9dff751a40ef82f724ae066db3c2a
Status: Downloaded newer image for getumbrel/auth-server@sha256:b4a4b37896911a85fb74fa159e010129abd9dff751a40ef82f724ae066db3c2a
docker.io/getumbrel/auth-server@sha256:b4a4b37896911a85fb74fa159e010129abd9dff751a40ef82f724ae066db3c2a
STEP 6/8: Installing umbreld
/tmp/umbrel/packages/umbreld /tmp/uis
patching file source/modules/provision/provision.ts

I have successfully installed version UMBREL_VERSION="1.2.2"

The only thing that doesn't work is the terminal. Probably something in the settings?

**Comment by unhighghlow** [comment]
Well, that's strange. I would say it's an internet issue, but docker works fine... I will just update the script to use docker instead.

**Comment by unhighghlow** [comment]
It should now be fixed.
